# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sum_pb2 as sum__pb2


class addStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.add = channel.unary_unary(
        '/add/add',
        request_serializer=sum__pb2.addMsg.SerializeToString,
        response_deserializer=sum__pb2.addMsg.FromString,
        )


class addServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_addServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'add': grpc.unary_unary_rpc_method_handler(
          servicer.add,
          request_deserializer=sum__pb2.addMsg.FromString,
          response_serializer=sum__pb2.addMsg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'add', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class imageStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.image = channel.unary_unary(
        '/image/image',
        request_serializer=sum__pb2.imageMsg.SerializeToString,
        response_deserializer=sum__pb2.addMsg.FromString,
        )


class imageServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def image(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_imageServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'image': grpc.unary_unary_rpc_method_handler(
          servicer.image,
          request_deserializer=sum__pb2.imageMsg.FromString,
          response_serializer=sum__pb2.addMsg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'image', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
